ALTER TABLE birthdays ADD COLUMN IF NOT EXISTS phone_number VARCHAR(64);
ALTER TABLE birthdays ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE birthdays ADD COLUMN IF NOT EXISTS postal_code VARCHAR(32);
ALTER TABLE birthdays ADD COLUMN IF NOT EXISTS city VARCHAR(128);
ALTER TABLE birthdays ADD COLUMN IF NOT EXISTS country VARCHAR(128);
