ALTER TABLE users ADD COLUMN dashboard_upcoming_days INT NOT NULL DEFAULT 30;
ALTER TABLE users ADD COLUMN birthday_sort_field VARCHAR(16) NOT NULL DEFAULT 'date';
ALTER TABLE users ADD COLUMN birthday_sort_desc BOOLEAN NOT NULL DEFAULT FALSE;
