ALTER TABLE birthdays ADD COLUMN phone_number VARCHAR(64);
ALTER TABLE birthdays ADD COLUMN address TEXT;
ALTER TABLE birthdays ADD COLUMN postal_code VARCHAR(32);
ALTER TABLE birthdays ADD COLUMN city VARCHAR(128);
ALTER TABLE birthdays ADD COLUMN country VARCHAR(128);
