ALTER TABLE birthdays ADD COLUMN IF NOT EXISTS phone_number TEXT;
ALTER TABLE birthdays ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE birthdays ADD COLUMN IF NOT EXISTS postal_code TEXT;
ALTER TABLE birthdays ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE birthdays ADD COLUMN IF NOT EXISTS country TEXT;
